ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb.piridishop.shop
REDIS_HOST: redis.piridishop.shop
MYSQL_HOST: mysql.piridishop.shop 
RABBITMQ_HOST: rabbitmq.piridishop.shop 
CATALOGUE_HOST: catalogue.piridishop.shop
USER_HOST: user.piridishop.shop
CART_HOST: cart.piridishop.shop
SHIPPING_HOST: shipping.piridishop.shop
PAYMENT_HOST: payment.piridishop.shop